import { Mona_Sans } from "next/font/google";
import "./globals.css";

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Aayush's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={monaSans.variable}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
